version: 1

database settings:
    static catalogues:
        db: crossmatch_catalogues
        host: 127.0.0.1
        user: pessto
        password: p355t0

    transients:
        user: pessto
        password: p355t0
        db: ps13pipublic
        host: 127.0.0.1


# SSH TUNNEL - if a tunnel is required to connect to the database(s) then add setup here
# Note only one tunnel is setup - may need to change this to 2 tunnels in the future if 
# code, static catalogue database and transient database are all on seperate machines.
ssh tunnel:
    remote user: dry
    remote ip: starbase.mp.qub.ac.uk
    remote datbase host: pesstovm02
    port: 9002

workflow lists: 
    GARBAGE: 0
    CONFIRMED: 1
    GOOD: 2
    POSSIBLE: 3
    EYEBALL: 4
    ATTIC: 5
    ZOO: 6
    UNLISTED: None 

qub list to classify: EYEBALL

search parameter id: 100


search radii:
        angular:
            galaxies:
                kepler: 30.0
                ned spec: 40.0
                sdss spec: 40.0
                ned phot: 20.0
                sdss phot: 20.0
                sdss faint stars: 20.0
            agn:
                milliquas: 3.0
                veron: 2.0
                ned: 2.0
                sdss: 2.0
            nuclear transient:
                ned: 3.0
                sdss spec: 3.0
                sdss phot: 0.5
            stars:
                ps1ubercal: 1.0
                sdss: 19.0
                2mass: 1.0
                gsc: 1.0
        physical:
            galaxies: 15.0
            nuclear transients: 0.5

classifications: 
    UNCLASSIFIED:
        human: unclassified
        flag: 0
    ORPHAN:
        human: orphan 
        flag: 1
    VARIABLESTAR:
        human: variablestar 
        flag: 2
    NT:
        human: nt           
        flag: 4
    AGN:
        human: agn          
        flag: 8
    SN:
        human: sn           
        flag: 16
    MISC:
        human: miscellaneous
        flag: 32
    TDE:
        human: tde          
        flag: 64
    LENS:
        human: lens         
        flag: 128
    MOVER:
        human: mover        
        flag: 256
    BRIGHT:
        human: bright       
        flag: 512
    KEPLER:
        human: kepler     
        flag: 1024


search algorithm:
    sdss qso:
        angular radius arcsec: 2.0
        transient classification: AGN
        database table: tcs_cat_v_sdss_dr9_spect_qsos
        stop algorithm on match: True
        match nearest source only: True
    milliquas:
        angular radius arcsec: 3.0
        transient classification: AGN
        database table: tcs_cat_milliquas
        stop algorithm on match: True
        match nearest source only: True
    veron:
        angular radius arcsec: 2.0
        transient classification: AGN
        database table: tcs_veron_cat
        stop algorithm on match: True
        match nearest source only: True
    ned qso:
        angular radius arcsec: 2.0
        transient classification: AGN
        database table: tcs_cat_v_ned_qsos
        stop algorithm on match: True
        match nearest source only: True
    ned nt:
        angular radius arcsec: 3.0
        physical radius kpc: 0.5
        transient classification: NT
        database table: tcs_cat_v_ned_galaxies
        stop algorithm on match: True
        match nearest source only: True
    sdss spec nt:
        angular radius arcsec: 3.0
        physical radius kpc: 0.5
        transient classification: NT
        database table: tcs_cat_v_sdss_dr9_spect_galaxies
        stop algorithm on match: True
        match nearest source only: True
    sdss phot nt: 
        angular radius arcsec: 0.5
        transient classification: NT
        database table: tcs_cat_v_sdss_dr9_galaxies_notspec
        stop algorithm on match: True
        match nearest source only: True
    ps1 md nt:
        angular radius arcsec: 0.5
        transient classification: NT
        database table: tcs_cat_v_ps1_medium_deep_ref_galaxies
        stop algorithm on match: True
        match nearest source only: True
    ned spec sn:
        angular radius arcsec: 40.0
        physical radius kpc: 15.0
        transient classification: SN
        database table: tcs_cat_v_ned_galaxies
        stop algorithm on match: True
        match nearest source only: True
    sdss spec sn:
        angular radius arcsec: 40.0
        physical radius kpc: 15.0
        transient classification: SN
        database table: tcs_cat_v_sdss_dr9_spect_galaxies
        stop algorithm on match: True
        match nearest source only: True
    ned phot sn:
        angular radius arcsec: 20.0
        transient classification: SN
        database table: tcs_cat_v_ned_galaxies
        stop algorithm on match: True
        match nearest source only: True
    sdss phot sn:
        angular radius arcsec: 20.0
        transient classification: SN
        database table: tcs_cat_v_sdss_dr9_galaxies_notspec
        stop algorithm on match: True
        match nearest source only: True
    sdss faint stars sn:
        angular radius arcsec: 20.0
        transient classification: SN
        database table: tcs_cat_v_sdss_dr9_stars
        mag column: petroMag_r
        faint limit: 21.0
        stop algorithm on match: True
        match nearest source only: True
    2mass faint stars sn:
        angular radius arcsec: 1.0
        transient classification: SN
        database table: tcs_cat_v_2mass_psc_noextended
        mag column: j_m
        faint limit: 18.0
        stop algorithm on match: True
        match nearest source only: True
    gsc faint stars sn:
        angular radius arcsec: 1.0
        transient classification: SN
        database table: tcs_cat_v_guide_star_ps
        mag column: VMag
        faint limit: 20.0
        stop algorithm on match: True
        match nearest source only: True
    ps1 ubercal star:
        angular radius arcsec: 1.0
        transient classification: VARIABLESTAR
        database table: tcs_cat_ps1_ubercal_stars
        stop algorithm on match: True
        match nearest source only: True
    sdss star:
        angular radius arcsec: 19.0
        transient classification: VARIABLESTAR
        database table: tcs_cat_v_sdss_dr9_stars
        stop algorithm on match: True
        match nearest source only: True
    2mass star:
        angular radius arcsec: 1.0
        transient classification: VARIABLESTAR
        database table: tcs_cat_v_2mass_psc_noextended
        stop algorithm on match: True
        match nearest source only: True
    gsc star:
        angular radius arcsec: 1.0
        transient classification: VARIABLESTAR
        database table: tcs_cat_v_guide_star_ps
        stop algorithm on match: True
        match nearest source only: True


supplementary search:
    kepler galaxy:
        angular radius arcsec: 30.0
        transient classification: KEPLER
        database table: tcs_cat_kepler_k2
        stop algorithm on match: True
        match nearest source only: True



# Hash of table names.  Produces list containing list of columns and table id.
CAT_ID_RA_DEC_COLS:
    'tcs_transient_objects': [['id', 'ra_psf', 'dec_psf'], 0]
    'tcs_2mass_psc_cat': [['designation', 'ra', 'decl'], 1]
    'tcs_cat_v_2mass_psc_noextended': [['designation', 'ra', 'decl'], 1]
    'tcs_2mass_xsc_cat': [['designation', 'ra', 'decl'], 2]
    # Remember that RA and DEC are in RADIANS here
    'tcs_guide_star_cat': [['hstID', 'RightAsc', 'Declination'], 3]
    # Remember that RA and DEC are in RADIANS here
    'tcs_cat_v_guide_star_ps': [['hstID', 'RightAsc', 'Declination'], 3]
    'tcs_ned_cat': [['Object_Name', 'RA_deg', 'DEC_deg', 'Redshift_1'], 4]
    # This and the following 3 views given same catalogue ID as base NED
    # catalogue
    'tcs_cat_v_ned_not_gal_qso': [['Object_Name', 'RA_deg', 'DEC_deg', 'Redshift_1'], 4]
    'tcs_cat_v_ned_qsos': [['Object_Name', 'RA_deg', 'DEC_deg', 'Redshift_1'], 4]
    'tcs_cat_v_ned_xrays': [['Object_Name', 'RA_deg', 'DEC_deg', 'Redshift_1'], 4]
    'tcs_cat_v_ned_galaxies': [['Object_Name', 'RA_deg', 'DEC_deg', 'Redshift_1'], 4]
    'tcs_sdss_galaxies_cat': [['Objid', 'ra', 'dec_', 'z'], 5]
    # Not spectroscopic galaxies
    'tcs_cat_v_sdss_galaxies_notspec': [['Objid', 'ra', 'dec_', 'z'], 5]
    'tcs_sdss_spect_galaxies_cat': [['Objid', 'ra', 'dec_', 'z'], 6]
    'tcs_sdss_stars_cat': [['Objid', 'ra', 'dec_'], 7]
    'tcs_veron_cat': [['recno', 'viz_RAJ2000', 'viz_DEJ2000', 'z'], 8]
    'tcs_cat_deep2dr3': [['OBJNAME', 'RA_deg', 'DEC_deg', 'Z'], 9]
    'tcs_cat_md01_ned': [['Object_Name', 'RA_deg', 'DEC_deg', 'Redshift'], 10]
    'tcs_cat_md02_ned': [['Object_Name', 'RA_deg', 'DEC_deg', 'Redshift'], 11]
    'tcs_cat_md03_ned': [['Object_Name', 'RA_deg', 'DEC_deg', 'Redshift'], 12]
    'tcs_cat_md04_ned': [['Object_Name', 'RA_deg', 'DEC_deg', 'Redshift'], 13]
    'tcs_cat_md05_ned': [['Object_Name', 'RA_deg', 'DEC_deg', 'Redshift'], 14]
    'tcs_cat_md06_ned': [['Object_Name', 'RA_deg', 'DEC_deg', 'Redshift'], 15]
    'tcs_cat_md07_ned': [['Object_Name', 'RA_deg', 'DEC_deg', 'Redshift'], 16]
    'tcs_cat_md08_ned': [['Object_Name', 'RA_deg', 'DEC_deg', 'Redshift'], 17]
    'tcs_cat_md09_ned': [['Object_Name', 'RA_deg', 'DEC_deg', 'Redshift'], 18]
    'tcs_cat_md10_ned': [['Object_Name', 'RA_deg', 'DEC_deg', 'Redshift'], 19]
    'tcs_cat_md01_chiappetti2005': [['recno', 'viz_RAJ2000', 'viz_DEJ2000'], 20]
    'tcs_cat_md01_pierre2007': [['recno', 'viz_RAJ2000', 'viz_DEJ2000'], 21]
    'tcs_cat_md02_giacconi2002': [['recno', 'viz_RAJ2000', 'viz_DEJ2000'], 22]
    'tcs_cat_md02_lefevre2004': [['recno', 'viz_RAJ2000', 'viz_DEJ2000', 'z'], 23]
    'tcs_cat_md02_lehmer2005': [['recno', 'viz_RAJ2000', 'viz_DEJ2000'], 24]
    'tcs_cat_md02_virani2006': [['recno', 'viz_RAJ2000', 'viz_DEJ2000'], 25]
    'tcs_cat_md04_hasinger2007': [['recno', 'viz_RAJ2000', 'viz_DEJ2000'], 26]
    'tcs_cat_md04_trump2007': [['recno', 'viz_RAJ2000', 'viz_DEJ2000', 'z'], 27]
    'tcs_cat_md05_brunner2008': [['recno', 'viz_RAJ2000', 'viz_DEJ2000'], 28]
    'tcs_cat_md07_laird2009': [['recno', 'viz_RAJ2000', 'viz_DEJ2000'], 29]
    'tcs_cat_md07_nandra2005': [['recno', 'viz_RAJ2000', 'viz_DEJ2000'], 30]
    'tcs_cat_md08_manners2003': [['recno', 'viz_RAJ2000', 'viz_DEJ2000'], 31]
    'tcs_cat_sdss_stars_galaxies': [['Objid', 'ra', 'dec_'], 32]
    'tcs_cat_v_sdss_starsgalaxies_stars': [['Objid', 'ra', 'dec_'], 32]
    'tcs_cat_v_sdss_starsgalaxies_galaxies': [['Objid', 'ra', 'dec_'], 32]
    'tcs_cat_sdss_lrg': [['Objid', 'ra', 'dec_'], 33]
    'tcs_cat_slacs': [['Objid', 'ra', 'dec_'], 34]
    'tcs_cat_milliquas': [['id', 'ra_deg', 'dec_deg', 'z'], 35]
    'tcs_cat_sdss_dr9_photo_stars_galaxies': [['objID', 'ra', 'dec_', 'z_'], 36]
    'tcs_cat_v_sdss_dr9_galaxies_notspec': [['objID', 'ra', 'dec_', 'z_'], 36]
    'tcs_cat_v_sdss_dr9_stars': [['objID', 'ra', 'dec_'], 36]
    'tcs_cat_sdss_dr9_spect_galaxies_qsos': [['objID', 'ra', 'dec_', 'z_'], 37]
    'tcs_cat_v_sdss_dr9_spect_galaxies': [['objID', 'ra', 'dec_', 'z_'], 37]
    'tcs_cat_v_sdss_dr9_spect_qsos': [['objID', 'ra', 'dec_', 'z_'], 37]
    'tcs_cat_rosat_faint_1x29': [['id', 'ra_deg', 'dec_deg'], 38]
    'tcs_cat_rosat_bright_1x10': [['id', 'ra_deg', 'dec_deg'], 39]
    'tcs_cfa_detections': [['cfa_designation', 'raDeg', 'decDeg'], 40]
    'tcs_cat_ps1_medium_deep_ref': [['id', 'ra', 'decl'], 41]
    'tcs_cat_v_ps1_medium_deep_ref_stars': [['id', 'ra', 'decl'], 41]
    'tcs_cat_v_ps1_medium_deep_ref_galaxies': [['id', 'ra', 'decl'], 41]
    # 2015-02-07 KWS Added ps1 ubercal star catalog form Doug and Eddie
    'tcs_cat_ps1_ubercal_stars': [['id', 'RA', 'Dec'], 43]

    # Added ATLAS Kepler 2 catalogue
    'tcs_cat_kepler_k2': [['name', 'ra_deg', 'dec_deg'], 42]

    # PESSTO database catalogues
    # 2014-04-08 KWS Added cbat views for SN and PSN

    'transientBucket': [['primaryKeyId', 'raDeg', 'decDeg'], 1000]
    'view_transientBucketMaster': [['primaryKeyId', 'raDeg', 'decDeg'], 1001]
    'atel_coordinates': [['primaryId', 'raDeg', 'decDeg'], 1002]
    'fs_chase': [['candidateID', 'ra_deg', 'dec_deg'], 1003]
    'view_fs_crts_css_summary': [['name', 'raDeg', 'decDeg'], 1004]
    'view_fs_crts_mls_summary': [['name', 'raDeg', 'decDeg'], 1005]
    'view_fs_crts_sss_summary': [['name', 'raDeg', 'decDeg'], 1006]
    'view_fs_lsq_summary': [['candidateID', 'ra_deg', 'dec_deg'], 1007]
    'view_fs_ogle_summary': [['name', 'raDeg', 'decDeg'], 1008]
    'cbats': [['name', 'raDeg', 'decDeg'], 1009]
    'view_cbats_sn': [['name', 'raDeg', 'decDeg'], 1010]
    'view_cbats_psn': [['name', 'raDeg', 'decDeg'], 1011]
    # 2015-03-16 KWS Added fs_brightsnlist_discoveries (bright SN list)
    'fs_brightsnlist_discoveries': [['name', 'raDeg', 'decDeg'], 1012]
    # 2015-04-21 KWS Added fs_asassn_sne and fs_asassn_transients
    'fs_asassn_sne': [['ID', 'RA', 'decl', 'Redshift'], 1013]
    'fs_asassn_transients': [['name', 'raDeg', 'decDeg'], 1014]

    # 2015-01-26 KWS Added tcs_photpipe_detections for quick & dirty
    # asteroid/fakes crossmatch
    'tcs_photpipe_detections': [['id', 'RA', 'Dec'], 2000]




logging settings:
    formatters:
        file_style:
            format: '* %(asctime)s - %(name)s - %(levelname)s (%(pathname)s > %(funcName)s > %(lineno)d) - %(message)s  '
            datefmt: '%Y/%m/%d %H:%M:%S'
        console_style:
            format: '* %(asctime)s - %(levelname)s: %(pathname)s:%(funcName)s:%(lineno)d > %(message)s'
            datefmt: '%H:%M:%S'
        html_style:
            format: '<div id="row" class="%(levelname)s"><span class="date">%(asctime)s</span>   <span class="label">file:</span><span class="filename">%(filename)s</span>   <span class="label">method:</span><span class="funcName">%(funcName)s</span>   <span class="label">line#:</span><span class="lineno">%(lineno)d</span> <span class="pathname">%(pathname)s</span>  <div class="right"><span class="message">%(message)s</span><span class="levelname">%(levelname)s</span></div></div>'
            datefmt: '%Y-%m-%d <span class= "time">%H:%M <span class= "seconds">%Ss</span></span>'
    handlers:
        console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: console_style
            stream: ext://sys.stdout
        file:
            class: logging.FileHandler
            level: DEBUG
            formatter: file_style
            filename: logger.log
            mode: w+
    root:
        level: INFO
        handlers: [file,console]
