version: 1

# THESE ADVANCED SETTINGS ARE COLLECTED WHEN USING CL-TOOLS, 
# BUT IF PACKAGE IS TO BE IMPORTED WITHIN OTHER CODE YOU NEED TO INCLUDE THIS PYTHON SNIPPET
# WHERE NEEDED IN THIS PACKAGE
# xt-collect-packages-advanced-settings

# MAXIMUM NUMBER OF TRANSIENTS TO REQUEST FROM DATABASE
database-batch-size: 20000
cpu-pool-size: False

stop-search-on-synonym-match: True

## SEARCH ALGORITHM SETTINGS
ned stream search radius arcec: 900
first pass ned search radius arcec: 240
ned stream refresh rate in days: 180
# THERE IS SOME ADJUSTMENT IN MANY CODE FOR ANGULARLY LARGE GALAXIES
galaxy radius stretch factor: 1.5
synonym radius arcsec: 1.5


ignore morphology list:
    - WISEAJ193037.70-521726.0
    - 2MASXJ19303773-5217259
    - Sagittarius Dwarf Spheroidal
    - SDSSJ093558.42+055602.5
    - CFN1064

search algorithm:
    ###### UNCLEAR OBJECT SEARCHES
    PS1 unclear:
        database table: tcs_view_unclear_ps1_dr1
        general:
            angular radius arcsec: 1.5
            synonym: UNCLEAR
    DESI LS DR10 unclear: 
        database table: tcs_view_unclear_desi_legacy_dr10
        general:
            angular radius arcsec: 1.5
            synonym: UNCLEAR
    SDSS DR12 unclear: 
        database table: tcs_view_unclear_sdss_photo_stars_galaxies_dr12
        general:
            angular radius arcsec: 1.5
            synonym: UNCLEAR
    NED unclear:
        database table: tcs_view_unclear_ned_stream
        general:
            angular radius arcsec: 1.5
            synonym: UNCLEAR
    NED spec unclear:
        database table: tcs_view_unclear_ned_stream
        general:
            physical radius kpc: 50.0
            angular radius arcsec: 60.0
            annotation: UNCLEAR
    GSC unclear:
        database table: tcs_view_unclear_guide_star_catalogue_v2_3
        general:
            angular radius arcsec: 1.5
            synonym: UNCLEAR
    2MASS unclear:
        database table: tcs_view_unclear_2mass_psc_final
        general:
            angular radius arcsec: 1.5
            synonym: UNCLEAR
    #### BRIGHT STAR SEARCHES
    PS1 bright stars:
        database table: tcs_view_bright_star_ps1_dr1
        general:
            angular radius arcsec: 7.
            synonym: VS
            association: BS
    DESI LS bright stars:
        database table: tcs_view_bright_star_desi_legacy_dr10
        general:
            angular radius arcsec: 7.
            synonym: VS
            association: BS
    gaia bright stars:
        database table: tcs_view_bright_star_gaia_dr3
        general:
            angular radius arcsec: 7.
            synonym: VS
            association: BS
    GSC v2.3 bright stars:
        database table: tcs_view_bright_star_guide_star_catalogue_v2_3
        general:
            angular radius arcsec: 7.
            synonym: VS
            association: BS
    SDSS dr12 bright stars:
        database table: tcs_view_bright_star_sdss_photo_stars_galaxies_dr12
        general:
            angular radius arcsec: 7.
            synonym: VS
            association: BS
    ###### REGULAR STAR SEARCHES
    2MASS stars:
        database table: tcs_view_star_2mass_psc_final
        general:
            angular radius arcsec: 1.5
            synonym: VS
    DESI LS stars:
        database table: tcs_view_star_desi_legacy_dr10
        general:
            angular radius arcsec: 1.5
            synonym: VS
    gaia stars:
        database table: tcs_view_star_gaia_dr3
        general:
            angular radius arcsec: 1.5
            synonym: VS
    GSC v2.3 stars:
        database table: tcs_view_star_guide_star_catalogue_v2_3
        general:
            angular radius arcsec: 1.5
            synonym: VS
    PS1 stars:
        database table: tcs_view_star_ps1_dr1
        general:
            angular radius arcsec: 1.5
            synonym: VS
    SDSS dr12 stars:
        database table: tcs_view_star_sdss_photo_stars_galaxies_dr12
        general:
            angular radius arcsec: 1.5
            synonym: VS
    ###### PHYSICAL GALAXY SEARCHES
    NED-D spec super big galaxies:
        # SUPER BIG > 2 ARCMIN
        database table: tcs_view_super_big_galaxy_ned_d_v17_1_2
        general:
            physical radius kpc: 50.0
            angular radius arcsec: 14000.0
            and within semi major axis: True
            synonym: NT
            association: SN
    NED spec super big galaxies:
        # SUPER BIG > 2 ARCMIN
        database table: tcs_view_super_big_galaxy_ned_stream
        general:
            physical radius kpc: 50.0
            angular radius arcsec: 1800.0
            and within semi major axis: True
            synonym: NT
            association: SN   
    NED-D spec big galaxies:
        # BIG > 20 ARCSEC
        database table: tcs_view_big_galaxy_ned_d_v17_1_2
        general:
            physical radius kpc: 50.0
            angular radius arcsec: 120.0
            and within semi major axis: True
            synonym: NT
            association: SN
    NED spec big galaxies:
        # BIG > 20 ARCSEC
        database table: tcs_view_big_galaxy_ned_stream
        general:
            physical radius kpc: 50.0
            angular radius arcsec: 120.0
            and within semi major axis: True
            synonym: NT
            association: SN  
    NED-D spec galaxies:
        database table: tcs_view_galaxy_ned_d_v17_1_2
        general:
            physical radius kpc: 50.0
            angular radius arcsec: 30.
            synonym: NT
            association: SN 
    NED spec galaxies:
        database table: tcs_view_galaxy_ned_stream
        general:
            physical radius kpc: 50.0
            angular radius arcsec: 30.
            synonym: NT
            association: SN
    SDSS spec galaxies:
        database table: tcs_view_galaxy_sdss_spect_galaxies_qsos_dr12
        general:
            physical radius kpc: 50.0
            angular radius arcsec: 60.0
            synonym: NT
            association: SN
    LASr galaxy:
        database table: tcs_view_galaxy_lasr_v1
        mag column: W1
        general:
            physical radius kpc: 50.0
            angular radius arcsec: 240.0
            synonym: NT
            association: SN
    ### ANGULAR GALAXY SEARCHES
    DESI LS big galaxies:
        # BIG > 20 ARCSEC. GALAXIES > 30.0 ARCSEC ALL CAUGHT BY NED/LASR
        database table: tcs_view_big_galaxy_desi_legacy_dr10
        general:
            angular radius arcsec:  30.0
            and within semi major axis: True
            synonym: NT
            association: SN
    GSC big galaxies:
        # BIG > 20 ARCSEC.  GALAXIES > 30.0 ARCSEC ALL CAUGHT BY NED/LASR
        database table: tcs_view_big_galaxy_guide_star_catalogue_v2_3
        general:
            angular radius arcsec: 30.0
            and within semi major axis: True
            synonym: NT
            association: SN
    NED-D phot galaxies:
        database table: tcs_view_galaxy_ned_d_v17_1_2
        general:
            angular radius arcsec: 10.
            and within semi major axis: True
            synonym: NT
            association: SN 
    NED phot galaxies:
        database table: tcs_view_galaxy_ned_stream
        general:
            angular radius arcsec: 10.
            and within semi major axis: True
            synonym: NT
            association: SN
    NED phot galaxy-like:
        database table: tcs_view_galaxy_like_ned_stream
        general:
            angular radius arcsec: 10.
            annotation: SN
    PS1 galaxies:
        database table: tcs_view_galaxy_ps1_dr1
        general:
            angular radius arcsec: 10.
            and within semi major axis: True
            synonym: NT
            association: SN
    2mass galaxies:
        database table: tcs_view_galaxy_2mass_xsc_final
        general:
            angular radius arcsec: 10.
            association: SN
            synonym: NT
    SDSS phot galaxies:
        database table: tcs_view_galaxy_sdss_photo_stars_galaxies_dr12
        general:
            angular radius arcsec: 10.
            association: SN
            synonym: NT
    GSC v2.3 galaxies:
        database table: tcs_view_galaxy_guide_star_catalogue_v2_3
        general:
            angular radius arcsec: 20.
            and within semi major axis: True
            synonym: NT
            association: SN
    DESI LS galaxies:
        database table: tcs_view_galaxy_desi_legacy_dr10
        general:
            angular radius arcsec: 20.0
            and within semi major axis: True
            synonym: NT
            association: SN

    #### AGN
    SDSS spec agn:
        database table: tcs_view_qso_sdss_spect_galaxies_qsos_dr12
        general:
            physical radius kpc: 50.0
            angular radius arcsec: 60.0
            synonym: AGN
            association: SN
    NED spec agn:
        database table: tcs_view_agn_ned_stream
        general:
            physical radius kpc: 50.0
            angular radius arcsec: 60.0
            synonym: AGN
            association: SN
    NED agn:
        database table: tcs_view_agn_ned_stream
        general:
            angular radius arcsec: 3.0
            synonym: AGN
            association: SN
    MILLIQUAS agn:
        database table: tcs_view_agn_milliquas_v8_0
        general:
            angular radius arcsec: 3.0
            synonym: AGN
            association: SN
    GAIA AGN:
        database table: tcs_view_qso_gaia_dr3
        mag column: G
        general:
            angular radius arcsec: 3.0
            synonym: AGN
            association: SN
    LASr agn:
        database table: tcs_view_agn_lasr_v1
        mag column: W1
        general:
            physical radius kpc: 50.0
            angular radius arcsec: 240.0
            synonym: AGN
            association: SN
    #### CVs
    downes cv:
        database table: tcs_view_cv_downes_cataclysmic_variables_final
        general:
            angular radius arcsec: 2.5
            synonym: CV
            association: CV
    ritter binaries:
        database table: tcs_view_cb_ritter_cataclysmic_binaries_v7_21
        general:
            angular radius arcsec: 2.5
            synonym: CV
            association: CV
